package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
	"github.com/talitore/smartass/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Asset)
// DB Table: Plural (assets)
// Resource: Plural (Assets)
// Path: Plural (/assets)
// View Template Folder: Plural (/templates/assets/)

// AssetsResource is the resource for the Asset model
type AssetsResource struct {
	buffalo.Resource
}

// List gets all Assets. This function is mapped to the path
// GET /assets
func (v AssetsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	assets := &models.Assets{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Assets from the DB
	if err := q.All(assets); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, assets))
}

// Show gets the data for one Asset. This function is mapped to
// the path GET /assets/{asset_id}
func (v AssetsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Asset
	asset := &models.Asset{}

	// To find the Asset the parameter asset_id is used.
	if err := tx.Find(asset, c.Param("asset_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, asset))
}

// New renders the form for creating a new Asset.
// This function is mapped to the path GET /assets/new
func (v AssetsResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Asset{}))
}

// Create adds a Asset to the DB. This function is mapped to the
// path POST /assets
func (v AssetsResource) Create(c buffalo.Context) error {
	// Allocate an empty Asset
	asset := &models.Asset{}

	// Bind asset to the html form elements
	if err := c.Bind(asset); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(asset)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, asset))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", T.Translate(c, "asset.created.success"))
	// and redirect to the assets index page
	return c.Render(201, r.Auto(c, asset))
}

// Edit renders a edit form for a Asset. This function is
// mapped to the path GET /assets/{asset_id}/edit
func (v AssetsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Asset
	asset := &models.Asset{}

	if err := tx.Find(asset, c.Param("asset_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, asset))
}

// Update changes a Asset in the DB. This function is mapped to
// the path PUT /assets/{asset_id}
func (v AssetsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Asset
	asset := &models.Asset{}

	if err := tx.Find(asset, c.Param("asset_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Asset to the html form elements
	if err := c.Bind(asset); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(asset)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, asset))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", T.Translate(c, "asset.updated.success"))
	// and redirect to the assets index page
	return c.Render(200, r.Auto(c, asset))
}

// Destroy deletes a Asset from the DB. This function is mapped
// to the path DELETE /assets/{asset_id}
func (v AssetsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Asset
	asset := &models.Asset{}

	// To find the Asset the parameter asset_id is used.
	if err := tx.Find(asset, c.Param("asset_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(asset); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", T.Translate(c, "asset.destroyed.success"))
	// Redirect to the assets index page
	return c.Render(200, r.Auto(c, asset))
}
